GET http://localhost:3000/users

###

GET http://localhost:3000/users/63c25c6a8d2a3a641abc2891

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Admin Name",
    "role": "admin"
}

###

DELETE http://localhost:3000/users/63c8dba8d36dcfc0f26d0077

###

PATCH http://localhost:3000/users/63c8dba8d36dcfc0f26d0077
Content-Type: application/json

{
    "name": "New Name",
    "role": "user"
}